Resources:
  ESDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      ElasticsearchVersion: 6.4
      ElasticsearchClusterConfig: 
        DedicatedMasterEnabled: false
        InstanceCount: 1
        ZoneAwarenessEnabled: false
        InstanceType: t2.small.elasticsearch
      EBSOptions: 
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: gp2
      SnapshotOptions: 
        AutomatedSnapshotStartHour: 0
      AccessPolicies: 
        Statement: 
          - Effect: Allow
            Principal: 
              AWS: '*'
            Action: 'es:*'
            Resource: 'arn:aws:es:${self:custom.region}:#{AWS::AccountId}:domain/${self:custom.stage}-es-domain-*/*'
      AdvancedOptions: 
        rest.action.multi.allow_explicit_index: true
